# db_constraints.db_exceptions

[](Generated by Ddoc from source/db_constraints/db_exceptions.d)

The db_exceptions module contains:
  + [UniqueConstraintException](#UniqueConstraintException)
  + [KeyedException](#KeyedException)
  + [CheckConstraintException](#CheckConstraintException)
  + [ForeignKeyException](#ForeignKeyException)

**License:**
[GPL-2.0](https://github.com/marmy28/db_constraints/blob/master/LICENSE)


**Authors:**
Matthew Armbruster


**Source:** [source/db_constraints/db_exceptions.d](https://github.com/marmy28/db_constraints/tree/master/source/db_constraints/db_exceptions.d)



***
<a name="UniqueConstraintException" href="#UniqueConstraintException"></a>
```d
class UniqueConstraintException: object.Exception;

```

Exception thrown on unique constraint violations.

***
<a name="UniqueConstraintException.this" href="#UniqueConstraintException.this"></a>
```d
this(string msg, string file = __FILE__, size_t line = __LINE__, Throwable next = null);

```
Parameters |
---|
*string msg*|
&nbsp;&nbsp;&nbsp;&nbsp;the message thrown with the unique constraint violation|
*string file*|
&nbsp;&nbsp;&nbsp;&nbsp;the file where the exception occurred|
*size_t line*|
&nbsp;&nbsp;&nbsp;&nbsp;the line number where the exception occurred|
*Throwable next*|
&nbsp;&nbsp;&nbsp;&nbsp;references the exception that was being handled when this one was generated|





***
<a name="KeyedException" href="#KeyedException"></a>
```d
class KeyedException: object.Exception;

```

Exception thrown on errors involved with keyed items.

***
<a name="KeyedException.this" href="#KeyedException.this"></a>
```d
this(string msg, string file = __FILE__, size_t line = __LINE__, Throwable next = null);

```
Parameters |
---|
*string msg*|
&nbsp;&nbsp;&nbsp;&nbsp;the message thrown|
*string file*|
&nbsp;&nbsp;&nbsp;&nbsp;the file where the exception occurred|
*size_t line*|
&nbsp;&nbsp;&nbsp;&nbsp;the line number where the exception occurred|
*Throwable next*|
&nbsp;&nbsp;&nbsp;&nbsp;references the exception that was being handled when this one was generated|





***
<a name="CheckConstraintException" href="#CheckConstraintException"></a>
```d
class CheckConstraintException: object.Exception;

```

Exception thrown on check constraint violations.

***
<a name="CheckConstraintException.this" href="#CheckConstraintException.this"></a>
```d
this(string msg, string file = __FILE__, size_t line = __LINE__, Throwable next = null);

```
Parameters |
---|
*string msg*|
&nbsp;&nbsp;&nbsp;&nbsp;the message thrown with the check constraint violation|
*string file*|
&nbsp;&nbsp;&nbsp;&nbsp;the file where the exception occurred|
*size_t line*|
&nbsp;&nbsp;&nbsp;&nbsp;the line number where the exception occurred|
*Throwable next*|
&nbsp;&nbsp;&nbsp;&nbsp;references the exception that was being handled when this one was generated|





***
<a name="ForeignKeyException" href="#ForeignKeyException"></a>
```d
class ForeignKeyException: object.Exception;

```

Exception thrown on foreign key violations.

***
<a name="ForeignKeyException.this" href="#ForeignKeyException.this"></a>
```d
this(string msg, string file = __FILE__, size_t line = __LINE__, Throwable next = null);

```
Parameters |
---|
*string msg*|
&nbsp;&nbsp;&nbsp;&nbsp;the message thrown with the foreign key violation|
*string file*|
&nbsp;&nbsp;&nbsp;&nbsp;the file where the exception occurred|
*size_t line*|
&nbsp;&nbsp;&nbsp;&nbsp;the line number where the exception occurred|
*Throwable next*|
&nbsp;&nbsp;&nbsp;&nbsp;references the exception that was being handled when this one was generated|







Copyright :copyright: 2015 | Page generated by [Ddoc](http://dlang.org/ddoc.html) on Sun Oct 11 17:39:16 2015

